language: ruby
rvm:
- 2.6.3

# make sure production-only gems are not installed
bundler_args: --without production

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
 - bundle exec cucumber
