language: ruby
rvm:
- 2.6.3

# make sure production-only gems are not installed
bundler_args: --without production

script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rspec spec"
  - "bundle exec rake cucumber"
