language: ruby
rvm:
- 2.6.3

# make sure production-only gems are not installed
bundler_args: --without production

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - RAILS_ENV=test ./bin/rails webpacker:compile
  - bundle exec rake db:create db:migrate RAILS_ENV=test
  - bundle exec rspec spec
  - bundle exec rake cucumber
